/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VmsRouteImport } from './routes/vms'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SshKeysRouteImport } from './routes/ssh-keys'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiTokensRouteImport } from './routes/api-tokens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVmsRouteImport } from './routes/admin/vms'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminIpPoolsRouteImport } from './routes/admin/ip-pools'
import { Route as AdminHaRouteImport } from './routes/admin/ha'
import { Route as AdminCreateVmRouteImport } from './routes/admin/create-vm'
import { Route as AdminClustersRouteImport } from './routes/admin/clusters'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'

const VmsRoute = VmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SshKeysRoute = SshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVmsRoute = AdminVmsRouteImport.update({
  id: '/admin/vms',
  path: '/admin/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIpPoolsRoute = AdminIpPoolsRouteImport.update({
  id: '/admin/ip-pools',
  path: '/admin/ip-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHaRoute = AdminHaRouteImport.update({
  id: '/admin/ha',
  path: '/admin/ha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateVmRoute = AdminCreateVmRouteImport.update({
  id: '/admin/create-vm',
  path: '/admin/create-vm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/admin/clusters',
  path: '/admin/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-tokens': typeof ApiTokensRoute
  '/billing': typeof BillingRoute
  '/console': typeof ConsoleRoute
  '/ssh-keys': typeof SshKeysRoute
  '/tickets': typeof TicketsRoute
  '/vms': typeof VmsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/create-vm': typeof AdminCreateVmRoute
  '/admin/ha': typeof AdminHaRoute
  '/admin/ip-pools': typeof AdminIpPoolsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vms': typeof AdminVmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-tokens': typeof ApiTokensRoute
  '/billing': typeof BillingRoute
  '/console': typeof ConsoleRoute
  '/ssh-keys': typeof SshKeysRoute
  '/tickets': typeof TicketsRoute
  '/vms': typeof VmsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/create-vm': typeof AdminCreateVmRoute
  '/admin/ha': typeof AdminHaRoute
  '/admin/ip-pools': typeof AdminIpPoolsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vms': typeof AdminVmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-tokens': typeof ApiTokensRoute
  '/billing': typeof BillingRoute
  '/console': typeof ConsoleRoute
  '/ssh-keys': typeof SshKeysRoute
  '/tickets': typeof TicketsRoute
  '/vms': typeof VmsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/create-vm': typeof AdminCreateVmRoute
  '/admin/ha': typeof AdminHaRoute
  '/admin/ip-pools': typeof AdminIpPoolsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vms': typeof AdminVmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-tokens'
    | '/billing'
    | '/console'
    | '/ssh-keys'
    | '/tickets'
    | '/vms'
    | '/admin/audit-logs'
    | '/admin/clusters'
    | '/admin/create-vm'
    | '/admin/ha'
    | '/admin/ip-pools'
    | '/admin/monitoring'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-tokens'
    | '/billing'
    | '/console'
    | '/ssh-keys'
    | '/tickets'
    | '/vms'
    | '/admin/audit-logs'
    | '/admin/clusters'
    | '/admin/create-vm'
    | '/admin/ha'
    | '/admin/ip-pools'
    | '/admin/monitoring'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vms'
  id:
    | '__root__'
    | '/'
    | '/api-tokens'
    | '/billing'
    | '/console'
    | '/ssh-keys'
    | '/tickets'
    | '/vms'
    | '/admin/audit-logs'
    | '/admin/clusters'
    | '/admin/create-vm'
    | '/admin/ha'
    | '/admin/ip-pools'
    | '/admin/monitoring'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTokensRoute: typeof ApiTokensRoute
  BillingRoute: typeof BillingRoute
  ConsoleRoute: typeof ConsoleRoute
  SshKeysRoute: typeof SshKeysRoute
  TicketsRoute: typeof TicketsRoute
  VmsRoute: typeof VmsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminClustersRoute: typeof AdminClustersRoute
  AdminCreateVmRoute: typeof AdminCreateVmRoute
  AdminHaRoute: typeof AdminHaRoute
  AdminIpPoolsRoute: typeof AdminIpPoolsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVmsRoute: typeof AdminVmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vms': {
      id: '/vms'
      path: '/vms'
      fullPath: '/vms'
      preLoaderRoute: typeof VmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssh-keys': {
      id: '/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof SshKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-tokens': {
      id: '/api-tokens'
      path: '/api-tokens'
      fullPath: '/api-tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vms': {
      id: '/admin/vms'
      path: '/admin/vms'
      fullPath: '/admin/vms'
      preLoaderRoute: typeof AdminVmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ip-pools': {
      id: '/admin/ip-pools'
      path: '/admin/ip-pools'
      fullPath: '/admin/ip-pools'
      preLoaderRoute: typeof AdminIpPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ha': {
      id: '/admin/ha'
      path: '/admin/ha'
      fullPath: '/admin/ha'
      preLoaderRoute: typeof AdminHaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-vm': {
      id: '/admin/create-vm'
      path: '/admin/create-vm'
      fullPath: '/admin/create-vm'
      preLoaderRoute: typeof AdminCreateVmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/admin/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTokensRoute: ApiTokensRoute,
  BillingRoute: BillingRoute,
  ConsoleRoute: ConsoleRoute,
  SshKeysRoute: SshKeysRoute,
  TicketsRoute: TicketsRoute,
  VmsRoute: VmsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminClustersRoute: AdminClustersRoute,
  AdminCreateVmRoute: AdminCreateVmRoute,
  AdminHaRoute: AdminHaRoute,
  AdminIpPoolsRoute: AdminIpPoolsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVmsRoute: AdminVmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
