/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VmsRouteImport } from './routes/vms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminClustersRouteImport } from './routes/admin/clusters'

const VmsRoute = VmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/admin/clusters',
  path: '/admin/clusters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vms': typeof VmsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vms': typeof VmsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vms': typeof VmsRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vms' | '/admin/clusters' | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vms' | '/admin/clusters' | '/admin/users'
  id: '__root__' | '/' | '/vms' | '/admin/clusters' | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VmsRoute: typeof VmsRoute
  AdminClustersRoute: typeof AdminClustersRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vms': {
      id: '/vms'
      path: '/vms'
      fullPath: '/vms'
      preLoaderRoute: typeof VmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/admin/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VmsRoute: VmsRoute,
  AdminClustersRoute: AdminClustersRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
